"""Core deterministic models and planning helpers for Cisco Network Configuration Assistant.

This package is intentionally device-write-free. It contains normalized data models,
network arithmetic, offline current state, capability/security profiles, templates/previews,
semantic diff planning/dry-run analysis/workflows, and validation.
"""

from .current_state import (
    CurrentAccessPortState,
    CurrentManagementState,
    CurrentNetworkState,
    CurrentStateBasis,
    CurrentStateError,
    CurrentTrunkState,
    CurrentVLANState,
)
from .dry_run import DeviceAwareDryRun, build_device_aware_dry_run
from .ipam import (
    GatewayStrategy,
    IPv4SubnetFacts,
    generate_sequential_networks,
    generate_vlan_series,
    subnet_facts,
)
from .models import (
    CapabilityState,
    DeviceCapability,
    DeviceFingerprint,
    ManagementIntent,
    NetworkIntent,
    ObservedState,
    PortIntent,
    PortMode,
    RoutingIntent,
    SecurityIntent,
    SecurityProfile,
    SegmentationAction,
    SegmentationIntent,
    SegmentationRule,
    UplinkIntent,
    VLANIntent,
)
from .plan_analysis import (
    ManagementImpactSummary,
    PlanAnalysis,
    RiskSummary,
    analyze_change_plan,
)
from .planner import (
    PLAN_SCHEMA_VERSION,
    ChangePlan,
    OperationReadiness,
    OperationType,
    PlannedOperation,
    RollbackSpec,
    RollbackStrategy,
    VerificationSpec,
    build_change_plan,
)
from .preview import (
    DesignPreview,
    PortPreviewRow,
    PreviewIssue,
    UplinkPreviewRow,
    VLANPreviewRow,
    build_design_preview,
)
from .profiles import (
    DeviceProfile,
    HardwareCapacity,
    ProfileError,
    ResourceLimits,
    generate_vlan_series_for_profile,
    load_cbs250_24t_4x_3_3_0_16_profile,
    load_device_profile,
    validate_intent_against_profile,
)
from .security_profiles import (
    SECURITY_PROFILE_SCHEMA_VERSION,
    ExpandedSecurityRule,
    RuleRequirement,
    RuleSeverity,
    SecurityExpansionResult,
    SecurityProfileDefinition,
    SecurityProfileError,
    SecurityRuleDefinition,
    expand_security_profile,
    get_security_profile,
    list_security_profiles,
)
from .templates import (
    TEMPLATE_SCHEMA_VERSION,
    RolePortCount,
    TemplateBuildResult,
    TemplateDefinition,
    TemplateError,
    TemplateId,
    TemplateRequest,
    TemplateRole,
    build_template,
    get_template_definition,
    list_templates,
)
from .validation import (
    ValidationIssue,
    ValidationResult,
    ValidationSeverity,
    validate_network_intent,
)
from .workflow import (
    DeviceAwareDesignPreview,
    TargetDevicePreview,
    build_device_aware_design_preview,
)

__all__ = [
    "CapabilityState",
    "ChangePlan",
    "CurrentAccessPortState",
    "CurrentManagementState",
    "CurrentNetworkState",
    "CurrentStateBasis",
    "CurrentStateError",
    "CurrentTrunkState",
    "CurrentVLANState",
    "DesignPreview",
    "DeviceAwareDesignPreview",
    "DeviceAwareDryRun",
    "DeviceCapability",
    "DeviceFingerprint",
    "DeviceProfile",
    "ExpandedSecurityRule",
    "GatewayStrategy",
    "HardwareCapacity",
    "IPv4SubnetFacts",
    "ManagementImpactSummary",
    "ManagementIntent",
    "NetworkIntent",
    "ObservedState",
    "OperationReadiness",
    "OperationType",
    "PLAN_SCHEMA_VERSION",
    "PlanAnalysis",
    "PlannedOperation",
    "PortIntent",
    "PortMode",
    "PortPreviewRow",
    "PreviewIssue",
    "ProfileError",
    "ResourceLimits",
    "RiskSummary",
    "RolePortCount",
    "RollbackSpec",
    "RollbackStrategy",
    "RoutingIntent",
    "RuleRequirement",
    "RuleSeverity",
    "SECURITY_PROFILE_SCHEMA_VERSION",
    "SecurityExpansionResult",
    "SecurityIntent",
    "SecurityProfile",
    "SecurityProfileDefinition",
    "SecurityProfileError",
    "SecurityRuleDefinition",
    "SegmentationAction",
    "SegmentationIntent",
    "SegmentationRule",
    "TEMPLATE_SCHEMA_VERSION",
    "TargetDevicePreview",
    "TemplateBuildResult",
    "TemplateDefinition",
    "TemplateError",
    "TemplateId",
    "TemplateRequest",
    "TemplateRole",
    "UplinkIntent",
    "UplinkPreviewRow",
    "VLANIntent",
    "VLANPreviewRow",
    "ValidationIssue",
    "ValidationResult",
    "ValidationSeverity",
    "VerificationSpec",
    "analyze_change_plan",
    "build_change_plan",
    "build_design_preview",
    "build_device_aware_design_preview",
    "build_device_aware_dry_run",
    "build_template",
    "expand_security_profile",
    "generate_sequential_networks",
    "generate_vlan_series",
    "generate_vlan_series_for_profile",
    "get_security_profile",
    "get_template_definition",
    "list_security_profiles",
    "list_templates",
    "load_cbs250_24t_4x_3_3_0_16_profile",
    "load_device_profile",
    "subnet_facts",
    "validate_intent_against_profile",
    "validate_network_intent",
]
