"""Core deterministic models and planning helpers for Cisco Network Configuration Assistant.

This package is intentionally device-write-free. It contains only normalized data models,
network arithmetic, offline capability profiles/templates/previews, and validation primitives.
"""

from .ipam import (
    GatewayStrategy,
    IPv4SubnetFacts,
    generate_sequential_networks,
    generate_vlan_series,
    subnet_facts,
)
from .models import (
    CapabilityState,
    DeviceCapability,
    DeviceFingerprint,
    ManagementIntent,
    NetworkIntent,
    ObservedState,
    PortIntent,
    PortMode,
    RoutingIntent,
    SecurityIntent,
    SecurityProfile,
    SegmentationAction,
    SegmentationIntent,
    SegmentationRule,
    UplinkIntent,
    VLANIntent,
)
from .preview import (
    DesignPreview,
    PortPreviewRow,
    PreviewIssue,
    UplinkPreviewRow,
    VLANPreviewRow,
    build_design_preview,
)
from .profiles import (
    DeviceProfile,
    HardwareCapacity,
    ProfileError,
    ResourceLimits,
    generate_vlan_series_for_profile,
    load_cbs250_24t_4x_3_3_0_16_profile,
    load_device_profile,
    validate_intent_against_profile,
)
from .templates import (
    TEMPLATE_SCHEMA_VERSION,
    RolePortCount,
    TemplateBuildResult,
    TemplateDefinition,
    TemplateError,
    TemplateId,
    TemplateRequest,
    TemplateRole,
    build_template,
    get_template_definition,
    list_templates,
)
from .validation import (
    ValidationIssue,
    ValidationResult,
    ValidationSeverity,
    validate_network_intent,
)

__all__ = [
    "CapabilityState",
    "DesignPreview",
    "DeviceCapability",
    "DeviceFingerprint",
    "DeviceProfile",
    "GatewayStrategy",
    "HardwareCapacity",
    "IPv4SubnetFacts",
    "ManagementIntent",
    "NetworkIntent",
    "ObservedState",
    "PortIntent",
    "PortMode",
    "PortPreviewRow",
    "PreviewIssue",
    "ProfileError",
    "ResourceLimits",
    "RolePortCount",
    "RoutingIntent",
    "SecurityIntent",
    "SecurityProfile",
    "SegmentationAction",
    "SegmentationIntent",
    "SegmentationRule",
    "TEMPLATE_SCHEMA_VERSION",
    "TemplateBuildResult",
    "TemplateDefinition",
    "TemplateError",
    "TemplateId",
    "TemplateRequest",
    "TemplateRole",
    "UplinkIntent",
    "UplinkPreviewRow",
    "VLANIntent",
    "VLANPreviewRow",
    "ValidationIssue",
    "ValidationResult",
    "ValidationSeverity",
    "build_design_preview",
    "build_template",
    "generate_sequential_networks",
    "generate_vlan_series",
    "generate_vlan_series_for_profile",
    "get_template_definition",
    "list_templates",
    "load_cbs250_24t_4x_3_3_0_16_profile",
    "load_device_profile",
    "subnet_facts",
    "validate_intent_against_profile",
    "validate_network_intent",
]
